e_munchkin/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('games/', include("games.urls")),
    path('', views.index, name='home'),
]

games/urls.py
from django.urls import path

from .views import view_encyclopedia
from .views import view_create_game
from .views import view_delete_gamer
from .views import view_edit_game
from .views import view_edit_gamer_order
from .views import view_edit_gamer
from .views import view_end_game
from .views import view_game_access
from .views import view_game_panel
from .views import view_gamer
from .views import view_help
from .views import view_kick_gamer
from .views import view_stats_game
from .views import view_update_stats

#from . import views as views

app_name = 'games'
urlpatterns = [
    # ex: /games/
    # path('', views.IndexView.as_view(), name='index'),
    path('encyclopedia/', view_encyclopedia.encyclopedia_view, name='encyclopedia'),

    # ex: /games/create/
    path('create/', view_create_game.CreateGameView.as_view(), name='create_game'),
    # ex: /games/1
    path('<int:pk>/', view_game_panel.GamePanelView.as_view(), name='game_panel'),
    # ex: /games/1/edit
    path('<int:pk>/edit/', view_edit_game.EditGameView.as_view(), name='edit_game'),
    # ex: /games/1/edit/gamer/order
    path('<int:pk>/edit/gamer/order', view_edit_gamer_order.EditGamerOrderView.as_view(), name='edit_gamer_order'),
    # ex: /games/1/end
    path('<int:pk>/end/', view_end_game.EndGameView.as_view(), name='end_game'),
    # ex: /games/1/edit/gamer/
    path('<int:pk>/edit/gamer/', view_edit_gamer.EditGamerView.as_view(), name='edit_gamer'),
    # ex: /games/1/end/update
    path('<int:pk>/end/update/', view_update_stats.update_stats, name='update_stats'),
    # ex: /games/1/stats
    path('<int:pk>/stats/', view_stats_game.StatsGameView.as_view(), name='game_stats'),

    # ex: /games/access/
    path('access/', view_game_access.GameAccessView.as_view(), name='game_access'),
    # ex: /games/ABCD/Humbert/join_game/
    # path('<gamepass>/<nick>/join_game/', views.join_game, name='join_game'),
    # ex: /games/gamer/5/
    path('gamer/<int:pk>/', view_gamer.GamerView.as_view(), name='gamer'),
    # ex: /games/gamer/5/lave
    path('gamer/<int:pk>/leave/', view_delete_gamer.DeleteGamerView.as_view(), name='delete_gamer'),
    # ex: /games/gamer/5/kick
    path('gamer/<int:pk>/kick/', view_kick_gamer.KickGamerView.as_view(), name='kick_gamer'),
    # ex: /games/help/
    path('help/', view_help.help_view, name='help')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

games/models/enum_gender.py
from enum import Enum, unique

@unique
class Gender(Enum):
    F = 'Female'
    M = 'Male'
    N = 'None'


GENDER_CHOICES = (
    (Gender.F.value,    'Female'),
    (Gender.M.value,    'Male'),
    (Gender.N.value,    'None'),
)
assert set(s.value for s in Gender) == set(dict(GENDER_CHOICES))

games/models/model_character_class.py
from django.db import models


class CharacterClass(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=1000, unique=True)

    def __str__(self):
        return self.name

games/models/model_character_race.py
from django.db import models


class CharacterRace(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=1000, unique=True)

    def __str__(self):
        return self.name

games/forms/form_edit_game.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from games.models.model_game import Game


class EditGameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'max_players', 'winning_level']
    name = forms.CharField(label=_("Name"))
    max_players = forms.IntegerField(label=_("Players number"), min_value=2, max_value=8, initial=6)
    winning_level = forms.IntegerField(label=_("Finish at level"), min_value=1, initial=10)

games/forms/form_gamer.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from games.models.model_game import Game
from games.models.model_gamer import Gamer
from games.models.model_character_race import CharacterRace
from games.models.model_character_class import CharacterClass
from games.models.enum_gender import GENDER_CHOICES


class GamerForm(forms.ModelForm):
    class Meta:
        model = Gamer
        fields = ['status', 'level', 'bonus', 'gender', 'race_slot_1', 'race_slot_2', 'class_slot_1', 'class_slot_2']
    status = forms.CharField(label=_('Status'), required=False)
    level = forms.IntegerField(label=_('Level'), initial=1, min_value=1)
    bonus = forms.IntegerField(label=_('Bonus'), initial=0)
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    race_slot_1 = forms.ModelChoiceField(queryset=CharacterRace.objects.all(), required=False, label=_('Race'))
    race_slot_2 = forms.ModelChoiceField(queryset=CharacterRace.objects.all(), required=False)
    class_slot_1 = forms.ModelChoiceField(queryset=CharacterClass.objects.all(), required=False, label=_('Class'))
    class_slot_2 = forms.ModelChoiceField(queryset=CharacterClass.objects.all(), required=False)

    def clean(self):
        cleaned_data = super(GamerForm, self).clean()

        race1 = cleaned_data['race_slot_1']
        race2 = cleaned_data['race_slot_2']
        class1 = cleaned_data['class_slot_1']
        class2 = cleaned_data['class_slot_2']

        if class2 is not None and class1 is None:
            cleaned_data['class_slot_1'] = class2
            cleaned_data['class_slot_2'] = None
            self.class_slot_1 = class2
            self.class_slot_2 = None

        if race2 is not None and race1 is None:
            cleaned_data['race_slot_1'] = race2
            cleaned_data['race_slot_2'] = None

        return cleaned_data

games/forms/form_gamer_edit.py
from .form_gamer import GamerForm
from django.utils.translation import ugettext_lazy as _
from games.models.model_gamer import Gamer


class GamerEditForm(GamerForm):
    class Meta(GamerForm.Meta):
        model = Gamer

    def __init__(self, *args, **kwargs):
        super(GamerEditForm, self).__init__(*args, **kwargs)
        self.fields.pop('status')

games/forms/form_gamer_order.py
from django import forms
from .form_gamer import GamerForm
from django.utils.translation import ugettext_lazy as _
from games.models.model_gamer import Gamer


class GamerOrderForm(GamerForm):
    class Meta(GamerForm.Meta):
        model = Gamer
        fields = GamerForm.Meta.fields + ['order']
    order = forms.IntegerField(label=_('Order'), initial=1, min_value=1, required=False)

    def clean(self):
        cleaned_data = super(GamerOrderForm, self).clean()
        order = self.cleaned_data['order']

        gamers = self.instance.game.gamers.all()
        error = False
        for gamer in gamers:
            if gamer.id is not self.instance.id and order is not None and gamer.order == order:
                error = True
        if error is True:
            raise forms.ValidationError(_('This order has already been taken :('))
        return cleaned_data

games/views/view_create_game.py
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from games.models.model_game import Game
import random
import string
from games.forms.form_edit_game import EditGameForm


def generate_game_code():

    code = ''

    already_exists = True

    unique = True

    while already_exists:
        code = code.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(Game._meta.get_field('game_code').max_length))

        for game in Game.objects.all():
            if game.game_code == code:
                unique = False

        already_exists = not unique

    return code

class CreateGameView(generic.CreateView):
    model = Game
    #fields = ['name', 'max_players', 'winning_level']
    template_name = 'games/game_create.html'
    form_class = EditGameForm

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('login')
        return super(CreateGameView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super(CreateGameView, self).get_context_data(**kwargs)
        data['hosted_games'] = Game.objects.filter(host=self.request.user, finished_at=None)
        return data

    def form_valid(self, form):
        form.instance.host = self.request.user
        form.instance.game_code = generate_game_code()
        form.save()
        return HttpResponseRedirect(reverse('games:game_panel', args=(form.instance.id,)))

games/views/view_delete_gamer.py
from django.http import HttpResponseRedirect, Http404
from django.views import generic
from django.urls import reverse
from games.models.model_gamer import Gamer


class DeleteGamerView(generic.DeleteView):
    model = Gamer
    template_name = 'games/delete_gamer.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().game.finished_at is not None:
            raise Http404("No gamer found")
        else:
            if self.request.user.is_authenticated:
                if self.get_object().user != self.request.user:
                    raise Http404("No gamer found")
            else:
                # if 'gamer_id' not in request.session:
                gamer_id = request.session.get('gamer_id', None)
                if gamer_id is None:
                    raise Http404("No gamer found")
                else:
                    # gamer_id = request.session['gamer_id']
                    if self.get_object().id != request.session['gamer_id']:
                        raise Http404("No gamer found")
        return super(DeleteGamerView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        request.session['gamer_id'] = None
        return super(DeleteGamerView, self).delete(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            return HttpResponseRedirect(reverse('games:gamer', args=(self.get_object().id,)))
        else:
            return super(DeleteGamerView, self).post(request, *args, **kwargs)

games/views/view_edit_game.py
from django.http import HttpResponseRedirect, Http404
from django.views import generic
from django.urls import reverse
from games.models.model_game import Game
from games.models.model_gamer import Gamer
from games.forms.form_edit_game import EditGameForm


class EditGameView(generic.UpdateView):
    #model = Game
    #fields = ['name', 'max_players', 'winning_level']
    template_name = 'games/game_edit.html'
    form_class = EditGameForm

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
                raise Http404("No game found")
        else:
            if self.get_object().host != self.request.user:
                raise Http404("No game found")
        return super(EditGameView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Game.objects

    def get_context_data(self, **kwargs):
        context = super(EditGameView, self).get_context_data(**kwargs)
        context['gamers'] = Gamer.objects.filter(game__id=self.kwargs['pk']).order_by('order')
        return context

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('games:edit_game', args=(form.instance.id,)))

games/views/view_edit_gamer.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from games.models.model_gamer import Gamer
from games.forms.form_gamer_edit import GamerEditForm


class EditGamerView(generic.UpdateView):
    model = Gamer
    form_class = GamerEditForm
    template_name = 'games/gamer_edit.html'

    def get_queryset(self):
        return Gamer.objects

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('games:end_game', args=(form.instance.game.id,)))

games/views/view_edit_gamer_order.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from games.models.model_gamer import Gamer
from games.forms.form_gamer_order import GamerOrderForm


class EditGamerOrderView(generic.UpdateView):
    model = Gamer
    form_class = GamerOrderForm
    template_name = 'games/gamer_edit.html'

    def get_queryset(self):
        return Gamer.objects

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('games:edit_game', args=(form.instance.game.id,)))

games/views/view_encyclopedia.py
from django.shortcuts import render
from games.models.model_character_race import CharacterRace
from games.models.model_character_class import CharacterClass

def encyclopedia_view(request):
        list_race = CharacterRace.objects.all()
        list_class = CharacterClass.objects.all()
        path = request.path
        context = {'list_race': list_race, 'list_class': list_class, 'path': path}

        return render(request, 'games/encyclopedia.html', context)

games/views/view_end_game.py
from django.views import generic
from games.models.model_game import Game


class EndGameView(generic.DetailView):
    model = Game
    template_name = 'games/game_end.html'

    def get_queryset(self):
        return Game.objects

games/views/view_game_access.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from games.models.model_game import Game
from games.models.model_gamer import Gamer
from games.forms.form_join import JoinForm


class GameAccessView(generic.FormView):                     # GUI for joining existing game
    template_name = 'games/game_access.html'
    form_class = JoinForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            data['gamers'] = Gamer.objects.filter(user=self.request.user)

        gamer_cookie = self.request.session.get('gamer_id', None)                 # COOKIE USED
        if gamer_cookie is not None:
            try:
                data['unregistered_gamer'] = Gamer.objects.get(pk=gamer_cookie)
            except Gamer.DoesNotExist:
                self.request.session['gamer_id'] = None
                gamer_cookie = None
        data['gamer_cookie'] = gamer_cookie
        return data

    def get_initial(self):
        initial = super(GameAccessView, self).get_initial()
        if self.request.user.is_authenticated:
            initial['nick'] = self.request.user.nick
            initial['user'] = self.request.user.id
        else:
            initial['user'] = None
            initial['gamer_id'] = self.request.session['gamer_id']

        return initial

    def form_valid(self, form):                            # Pass nickname and password to join_game view
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        game_pass = form.get_game_pass()
        nick = form.get_nick()

        game = Game.objects.get(game_code=game_pass)

        gamer = Gamer.objects.create(  # Create player and add to game if possible
            game=game,
            nick=nick
        )

        for x in range(1, game.max_players+1):
            try:
                gamegamer = Gamer.objects.get(game__game_code=game_pass, order=x)
            except Gamer.DoesNotExist:
                gamegamer = None
                gamer.order = x
                break
        self.request.session['gamer_id'] = gamer.id  # Add gamer id to actual session
        if self.request.user.is_authenticated:
            gamer.user = self.request.user
        gamer.save()

        return HttpResponseRedirect(reverse('games:gamer', args=(gamer.id,)))

games/views/view_game_panel.py
from django.views import generic
from games.models.model_game import Game
from games.models.model_gamer import Gamer


class GamePanelView(generic.DetailView):
    model = Game
    template_name = 'games/game_panel.html'

    def get_queryset(self):
        return Game.objects

    def get_context_data(self, **kwargs):
        context = super(GamePanelView, self).get_context_data(**kwargs)
        context['game'] = Game.objects.get(pk=self.kwargs['pk'])
        context['gamers'] = Gamer.objects.filter(game__id=self.kwargs['pk']).order_by('order')
        return context

games/templates/games/game_edit.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load i18n %}
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}" />

    <script type="text/javascript">
      var end_game_path = "{% url 'games:end_game' game.id%}";
      var game_panel_path = "{% url 'games:game_panel' game.id%}";
      var trans_yes = "{% trans 'Yes' %}";
      var trans_no = "{% trans 'No' %}";
      var message_yes = "{% trans 'Yes, I know' %}";
      var message_no = "{% trans 'Oh, really' %}?";

      var gamers = [];
      {% for gamer in gamers.all %}
        var temp = {
                  id:"{{ gamer.id }}",
                  nick:"{{ gamer.nick }}",
                  order:"{{ gamer.order }}",
          }
        gamers.push(temp);
      {% endfor %}
    </script>
    <script type="text/javascript" src="{% static 'games/scripts/game_edit_popup.js' %}"></script>
</head>

<h1>{% trans 'Edit your game' %}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div id="wrapper">
    <div {% if game.gamers.count > 0 %} id="first" {% endif %}>
        <form method="post">
            {% csrf_token %}
            <table align="center">
                {% for field in form %}
                    <tr>
                        <td align="right">{{ field.label_tag }}</td>
                        <td colspan="2">{{ field }}</td>
                    </tr>
                    <tr>
                        {% if field.help_text %}
                            <td colspan="3" align="center"><small style="color: #5c8af9 ">{{ field.help_text }}</small></td>
                        {% endif %}
                    </tr>
                    <tr>
                        {% for error in field.errors %}
                            <tr>
                                <td colspan="3" align="center"><small style="color: red">{{ error }}</small></td>
                            </tr>
                        {% endfor %}
                    </tr>
                {% endfor %}
                <tr>
                    <td> </td>
                    <td><input type="submit" value="{% trans 'Save' %}" class="green_button"/></td>
                </tr>
            </table>

        </form>
        <br />

    </div>

    {% if game.gamers.count > 0 %}
        <div id="second">
            <table width="50%" height="100%" cellpadding="2" cellspacing="1">
                <tr align="center">
                    <th style="border: 2px solid;background-color:white;">{% trans 'Order' %}</th>
                    <th style="border: 2px solid;background-color:white;">{% trans 'Nick' %}</th>
                    <th></th>
                    <th></th>
                </tr>
                {% for gamer in gamers %}
                <tr>
                    {% if gamer.order == None %}
                      <td align="center" style="border: 1px solid;background-color:white;"> </td>
                    {% else %}
                    <td align="center" style="border: 1px solid;background-color:white;">{{ gamer.order }}</td>
                    {% endif %}
                    <td align="left" style="border: 1px solid;background-color:white;">{{ gamer.nick }}</td>
                    <td align="center">
                      <form action="{% url 'games:edit_gamer_order' gamer.id%}">
                         <input type="submit" value="{% trans 'Edit' %}" class="blue_button"/>
                      </form>
                    </td>
                    <td align="center">
                      <form action="{% url 'games:kick_gamer' gamer.id%}" >
                         <input type="submit" value="{% trans 'Kick' %}" class="red_button"/>
                      </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
</div>

<br />

<table cellpadding="30">
  <tr>
    <td>
      <input type="button" id="DialogShow" value="{% trans 'End game' %}" class="red_button"/>

      <div id="dialog" style="display: none" title="{% trans 'Are you sure' %}?" align="center">
          {% trans 'Do you want to end' %} <b> {{ game.name }} </b> <br />
          {% trans 'and save all gamers stats' %}?
      </div>
    </td>
    <td>
      <input type="button" id="AlertShow" value="{% trans 'Back' %}" class="back_button"/>

      <div id="alert" style="display: none" title="{% trans 'Watch out' %}!" align="center">
          {% trans 'Some gamer does not have his order' %}!
      </div>
    </td>
</table>

{% endblock %}

games/templates/games/game_end.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load i18n %}
<head>

    <script>
      var path = "/games/{{ game.pk }}/end/";
    </script>
    <script type="text/javascript" src="{% static 'games/scripts/reload_page.js' %}"></script>
</head>

<h1>{% trans 'This is the end of the' %} {{ game.name }} </h1>

<table id="game_stats_table" width="80%" height="100%" border="3" cellpadding="5" cellspacing="4" align="center">
    <tr>
        <th> {% trans 'Statistics' %} </th>
    {% for gamer in game.gamers.all %}
        <th>{% trans 'Gamer' %} {{ forloop.counter }}</th>
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Nick' %}</th>
    {% for gamer in game.gamers.all %}
        <td>{{ gamer.nick }}</td>
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Level' %}</th>
    {% for gamer in game.gamers.all %}
        <td>{{ gamer.level }}</td>
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Bonus' %}</th>
    {% for gamer in game.gamers.all %}
        <td>{{ gamer.bonus }}</td>
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Gender' %}</th>
    {% for gamer in game.gamers.all %}
        <td>{{ gamer.gender }}</td>
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Race' %}</th>
    {% for gamer in game.gamers.all %}
        {% if gamer.race_slot_1 != None %}
        <td>{{ gamer.race_slot_1 }}</td>
        {% else %}
        <td> </td>
        {% endif %}
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Race' %} 2</th>
    {% for gamer in game.gamers.all %}
        {% if gamer.race_slot_2 != None %}
        <td>{{ gamer.race_slot_2 }}</td>
        {% else %}
        <td> </td>
        {% endif %}
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Class' %}</th>
    {% for gamer in game.gamers.all %}
        {% if gamer.class_slot_1 != None %}
        <td>{{ gamer.class_slot_1 }}</td>
        {% else %}
        <td> </td>
        {% endif %}
    {% endfor %}
    </tr>
    <tr>         <th>{% trans 'Class' %} 2</th>
    {% for gamer in game.gamers.all %}
        {% if gamer.class_slot_2 != None %}
        <td>{{ gamer.class_slot_2 }}</td>
        {% else %}
        <td> </td>
        {% endif %}
    {% endfor %}
    </tr>
    <tr>
        <th> {% trans 'Status' %} </th>
    {% for gamer in game.gamers.all %}
        {% if gamer.level >= gamer.game.winning_level %}
        <td> <font color="red">Winner</font> </td>
        {% else %}
        <td> </td>
        {% endif %}
    {% endfor %}
    </tr>
    <tr>
        <th></th>
    {% for gamer in game.gamers.all %}
        <td align="center">
          <form action="{% url 'games:edit_gamer' gamer.id%}">
            <input type="submit" value="{% trans 'Edit' %}" class="blue_button"/>
          </form>
        </td>
    {% endfor %}
    </tr>
</table>

<br />

<form action="{% url 'games:update_stats' game.id %}">
    <input type="submit" value="{% trans "That's right" %}" class="green_button"/>
</form>

{% endblock %}

games/templates/games/gamer.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load i18n %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}" />
<!--<link rel="stylesheet" type="text/css" href="{% static 'games/style2.css' %}" />-->

<script type="text/javascript" src="{% static 'games/scripts/increment.js' %}"></script>
<table align="center">
    <tr>
      <form action="{% url 'games:encyclopedia' %}">
        <table>
          <tr><td>
            <h1>{{ gamer.nick }} </h1>
          </td><td>
            <input type="submit" value="?" class="grey_small_button"/>
          </td></tr>
        </table>
      </form>
    </tr>
    <tr>
      <td align="center"><font color=#b32d00><h2>{{ gamer.game.name}}</h2></font><td>
    </tr>
</table>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post"> <!--action="" method="post">-->
    {% csrf_token %}
     <table align="center">
    {% for field in form %}
         {% if field is form.level or field is form.bonus %}
            <!-- integer fields -->
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>
                    <i class="btn btn-danger btn-sm" onclick="increment(-1, '{{ field.auto_id }}')">-</i>
                    {{ field }}
                    <i class="btn btn-success btn-sm" onclick="increment(1, '{{ field.auto_id }}')">+</i>
                </td>
            </tr>
         {% else %}
            {% if field is form.race_slot_2 %}
                {% if form.race_slot_1.value != None or gamer.race_slot_1 != None %}
                    <!-- Race field -->
                    <tr>
                        <td></td>
                        <td>
                            {{ field }}
                        </td>
                    </tr>
                {% endif %}
            {% else %}
                {% if field is form.class_slot_2 %}
                    {% if form.class_slot_1.value != None or gamer.class_slot_1 != None %}
                        <!-- Class field -->
                        <tr>
                            <td></td>
                            <td>
                                {{ field }}
                            </td>
                        </tr>
                    {% endif %}
                {% else %}
                    <tr>
                        <td>{{ field.label_tag }}</td>
                        <td>
                            {{ field }}
                        </td>
                    </tr>
                {% endif %}
            {% endif %}
         {% endif %}


        <tr>
        {% if field.help_text %}
            <td colspan="2" align="center"><small style="color: LightGray ">{{ field.help_text }}</small></td>
        {% endif %}
        </tr>

        <tr>
        {% for error in field.errors %}
            <tr>
          <td colspan="2" align="center"><small style="color: red">{{ error }}</small></td>
            </tr>
        {% endfor %}
        </tr>
    {% endfor %}
        </table>
    <br/>
    <input type="submit" value="{% trans 'Update' %}" class="green_button"/>
</form>
<br/>
<form action="{% url 'games:delete_gamer' gamer.id %}">
    <input type="submit" value="{% trans 'Withdraw from game' %}" class="red_button"/>
</form>

    {% for gamer in gamer.game.gamers.all %}
        {% if gamer.level >= gamer.game.winning_level and gamer.game.finished_at is None %}
        <div id="dialog" title="{% trans 'Wait, wait, wait...' %}" align="center">
            <p>{% trans 'I think we have a winner' %}...<br />{% trans 'But wait for game-master decision' %}</p>
        </div>
        <script>
            window.setTimeout(function () {
            location.reload();
            }, 5000);
        </script>

        {% endif %}
    {% endfor %}

<script type="text/javascript">

$("div#dialog").dialog({
                modal: true,
                closeOnEscape: false,
                open: function(event, ui) {
                $(".ui-dialog-titlebar-close", ui.dialog | ui).hide();
                }
});
</script>

    {% if gamer.winner or gamer.game.finished_at is not None %}
        <script>
        window.location.href = "{% url 'home' %}";
        </script>
    {% endif %}
{% endblock %}