e_munchkin/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('games/', include("games.urls")),
    path('', views.index, name='home'),
]

games/urls.py
from django.urls import path

from .views import view_encyclopedia
from .views import view_create_game
from .views import view_delete_gamer
from .views import view_edit_game
from .views import view_edit_gamer_order
from .views import view_edit_gamer
from .views import view_end_game
from .views import view_game_access
from .views import view_game_panel
from .views import view_gamer
from .views import view_help
from .views import view_kick_gamer
from .views import view_stats_game
from .views import view_update_stats

#from . import views as views

app_name = 'games'
urlpatterns = [
    # ex: /games/
    # path('', views.IndexView.as_view(), name='index'),
    path('encyclopedia/', view_encyclopedia.encyclopedia_view, name='encyclopedia'),

    # ex: /games/create/
    path('create/', view_create_game.CreateGameView.as_view(), name='create_game'),
    # ex: /games/1
    path('<int:pk>/', view_game_panel.GamePanelView.as_view(), name='game_panel'),
    # ex: /games/1/edit
    path('<int:pk>/edit/', view_edit_game.EditGameView.as_view(), name='edit_game'),
    # ex: /games/1/edit/gamer/order
    path('<int:pk>/edit/gamer/order', view_edit_gamer_order.EditGamerOrderView.as_view(), name='edit_gamer_order'),
    # ex: /games/1/end
    path('<int:pk>/end/', view_end_game.EndGameView.as_view(), name='end_game'),
    # ex: /games/1/edit/gamer/
    path('<int:pk>/edit/gamer/', view_edit_gamer.EditGamerView.as_view(), name='edit_gamer'),
    # ex: /games/1/end/update
    path('<int:pk>/end/update/', view_update_stats.update_stats, name='update_stats'),
    # ex: /games/1/stats
    path('<int:pk>/stats/', view_stats_game.StatsGameView.as_view(), name='game_stats'),

    # ex: /games/access/
    path('access/', view_game_access.GameAccessView.as_view(), name='game_access'),
    # ex: /games/ABCD/Humbert/join_game/
    # path('<gamepass>/<nick>/join_game/', views.join_game, name='join_game'),
    # ex: /games/gamer/5/
    path('gamer/<int:pk>/', view_gamer.GamerView.as_view(), name='gamer'),
    # ex: /games/gamer/5/lave
    path('gamer/<int:pk>/leave/', view_delete_gamer.DeleteGamerView.as_view(), name='delete_gamer'),
    # ex: /games/gamer/5/kick
    path('gamer/<int:pk>/kick/', view_kick_gamer.KickGamerView.as_view(), name='kick_gamer'),
    # ex: /games/help/
    path('help/', view_help.help_view, name='help')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from .views import view_sign_up
from .views import view_user_stats
from .views import view_delete_user
from .views import view_change_password
from .views import view_custom_user_update

urlpatterns = [
    path('signup/', view_sign_up.SignUp.as_view(), name='signup'),
    path('<int:pk>/stats/', view_user_stats.UserStats.as_view(), name='user_stats'),
    path('account/<int:pk>/leave/', view_delete_user.DeleteUserView.as_view(), name='delete_user'),
    path('account/password', view_change_password.change_password, name='change_password'),
    path('account', view_custom_user_update.CustomUser_update, name='edit_profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class CustomUser(AbstractUser):
    username = models.CharField(_('username'), max_length=30, unique=True,
                                help_text=_('Required. 30 characters or fewer. Letters, numbers and '
                                            '@/./+/-/_ characters'))
    nick = models.CharField(_('nick name'), max_length=50, unique=False, help_text=_("It will be used for games. You can change it later."))
    email = models.EmailField(_('email address'), max_length=254, unique=True, help_text=_("Required to account verification."))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    updatedat = models.DateTimeField(verbose_name='updated at',  default=timezone.now)

    def __str__(self):
        return self.username

users/forms/form_custom_user_change.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.utils.translation import ugettext_lazy as _
from users.models import CustomUser


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'nick')

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields.pop('password')

    def clean_password(self):
        password1 = self.cleaned_data.get('password1', None)
        password2 = self.cleaned_data.get('password2', None)
        return self.cleaned_data

users/forms/form_custom_user_creation.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput, help_text=_("Your password must contain at least 8 characters."))
    password2 = forms.CharField(label=_("Password confirmation"), widget=forms.PasswordInput, help_text=_("Enter the same password as above, for verification."))

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'nick')

users/views/view_change_password.py
from django.shortcuts import redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return redirect('change_password')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/change_password.html', {
        'form': form
    })

users/views/view_custom_user_update.py
from django.shortcuts import redirect
from users.forms.form_custom_user_change import  CustomUserChangeForm
from django.shortcuts import render


def CustomUser_update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('edit_profile')
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'users/edit_profile.html', {
        'user_form': form,
    })

users/views/view_delete_user.py
from django.views import generic
from users.models import CustomUser
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.utils.translation import gettext as _


NO_USER_FOUND_MESSAGE = "No user found"


class DeleteUserView(generic.DeleteView):
    model = CustomUser
    template_name = 'users/delete_user.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            raise Http404(NO_USER_FOUND_MESSAGE)
        else:
            if self.get_object() != self.request.user:
                raise Http404(NO_USER_FOUND_MESSAGE)
        return super(DeleteUserView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        request.session['user_id'] = None
        return super(DeleteUserView, self).delete(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            return HttpResponseRedirect(reverse('edit_profile'))
        else:
            return super(DeleteUserView, self).post(request, *args, **kwargs)

users/views/view_sign_up.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect
from users.forms.form_custom_user_creation import CustomUserCreationForm


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('home')
        return super(SignUp, self).dispatch(request, *args, **kwargs)

users/views/view_user_stats.py
from django.views import generic
from users.models import CustomUser
from games.models.model_game import Game
from games.models.model_gamer import Gamer
from django.db.models import Q
from django.http import Http404
#from django.contrib import messages
from django.utils.translation import gettext as _


NO_USER_FOUND_MESSAGE = "No user found"


class UserStats(generic.DetailView):
    model = CustomUser
    template_name = 'users/user_stats.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            raise Http404(NO_USER_FOUND_MESSAGE)
        else:
            if self.get_object() != self.request.user:
                raise Http404(NO_USER_FOUND_MESSAGE)
        return super(UserStats, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super(UserStats, self).get_context_data(**kwargs)
        data['hosted_games'] = Game.objects.filter(host=self.request.user, finished_at=None)
        data['hosted_end_games'] = Game.objects.filter(host=self.request.user).filter(~Q(finished_at=None))
        data['gamers'] = Gamer.objects.filter(user=self.request.user, game__finished_at=None)
        data['gamers_end'] = Gamer.objects.filter(user=self.request.user).filter(~Q(game__finished_at=None))
        return data

users/templates/users/change_password.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}

{% if not user.is_authenticated %}
    <script>
        window.location.href = "{% url 'home' %}";
    </script>
{% endif %}

<h1>{% trans 'Change account details' %}</h1>

<br />

<h3>{% trans 'Change password' %}</h3>
<form method="post">
    {% csrf_token %}
    <table align="center">
        {% for field in form %}
            <tr>
                <td align="right">{{ field.label_tag }}</td>
                <td>{{ field }}</td>
            </tr>
            <tr>
                {% for error in field.errors %}
                    <tr>
                        <td colspan="2" align="center"><small style="color: red">{{ error }}</small></td>
                    </tr>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
    <input type="submit" value="{% trans 'Save changes' %}" class="green_button"/>
</form>

<br />

    <form action="{% url 'edit_profile' %}">
        <input type="submit" value="{% trans 'Back' %}" class="back_button"/>
    </form>

{% endblock %}

users/templates/users/delete_user.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load i18n %}

<link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}" />

<h1>{% trans 'Do you want to leave us' %}?!</h1>
<form method="post">{% csrf_token %}
    <p><strong>{% trans 'Are you sure you want to delete your account?' %}</strong></p>
    <br/>
    <p>{% trans 'This will irreversibly remove your hosted games and gamers' %}.</p>
    <br/>
    <p>{% trans 'All of your current stats will be lost' %}.</p>
    <br/>
    <p>{% trans 'Are you sure you want to proceed' %}?</p>
    <br/>
    <table align="center">
        <tr>
            <td>
                <input type="submit" class="btn btn-success" value="{% trans 'Yes' %}">
            </td>
            <td width="20px"></td>
            <td>
                <input type="submit" name="cancel" class="btn btn-danger" value="{% trans 'No' %}">
            </td>
        </tr>
    </table>
</form>
{% endblock %}

users/templates/users/edit_profile.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}

{% if not user.is_authenticated %}
    <script>
        window.location.href = "{% url 'home' %}";
    </script>
{% endif %}

<h1> {% trans 'Change account details' %}</h1>

<br />

<h3> {% trans 'Change profile details' %}</h3>
    <form method="post">
        {% csrf_token %}
            <table align="center">
                {% for field in user_form %}

                    {% if field.label_tag is not 'username' %}
                        <tr>
                            <td>{{ field.label_tag }}</td>
                            <td>{{ field }}</td>
                        </tr>
                        <tr>
                            {% for error in field.errors %}
                                <tr>
                                    <td colspan="2" align="center"><small style="color: red">{{ error }}</small></td>
                                </tr>
                            {% endfor %}
                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
        <input type="submit" value="{% trans 'Save changes' %}" class="green_button"/>
  </form>
<hr>

<table>
    <tr>
    <td>
        <form action="{% url 'change_password' %}">
            <input type="submit" value="{% trans 'Change password' %}" class="blue_button"/>
        </form>
    </td>
    <td>
        <form action="{% url 'delete_user' user.id %}">
            <input type="submit" value="{% trans 'Delete account' %}" class="red_button"/>
        </form>
    </td>
    </tr>
</table>

{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

  <h2>{% trans 'Sign up' %}</h2>
  <form method="post">
    {% csrf_token %}
        <table align="center">
    {% for field in form %}
        <tr>
        <td>{{ field.label_tag }}</td>
        <td>{{ field }}</td>
        </tr>
        <tr>
        {% if field.help_text %}
            <td colspan="2" align="center"><small style="color: #5c8af9 ">{{ field.help_text }}</small></td>
        {% endif %}
        </tr>
        <tr>
        {% for error in field.errors %}
            <tr>
          <td colspan="2" align="center"><small style="color: red">{{ error }}</small></td>
            </tr>
        {% endfor %}
        </tr>
    {% endfor %}
        </table>
    <input type="submit" value="{% trans 'Sign up' %}" class="green_button"/>
  </form>

{% endblock %}

users/templates/users/user_stats.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h1> {% trans 'Hey' %} <font color="orange">{{ user.username }}</font>, {% trans "that's all yours" %}! </h1>
<hr>
<h4> {% trans 'Hosted games' %} </h4>
{% if hosted_games %}
    <p>{% trans 'Games you are currently hosting' %}:</p>
    <table width="50%" height="100%" border="1" cellpadding="2" cellspacing="1" bgcolor="white">
        <tr>
            <th> {% trans 'Game name' %} </th>
            <th> {% trans 'Game code' %} </th>
            <th> {% trans 'Players' %} </th>
            <th> {% trans 'Game created at' %}</th>
        </tr>
        {% for game in hosted_games %}
            <tr>
                <td><a href="{% url 'games:game_stats' game.id %}">{{ game.name }}</a></td>
                <td>{{ game.game_code }}</td>
                <td>{{ game.gamers.count }}/{{ game.max_players }}</td>
                <td>{{ game.created_at }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>{% trans 'You are not hosting any games' %}.</p>
{% endif %}

<br />

{% if hosted_end_games %}
    <p>{% trans 'Games you have been hosting' %}:</p>
    <table width="50%" height="100%" border="1" cellpadding="2" cellspacing="1" bgcolor="white">
        <tr>
            <th> {% trans 'Game name' %} </th>
            <th> {% trans 'Players' %} </th>
            <th> {% trans 'Game created at' %}</th>
            <th> {% trans 'Game finished at' %}</th>
            <th> {% trans 'Game winner' %} </th>
        </tr>
        {% for game in hosted_end_games %}
            <tr>
                <td><a href="{% url 'games:game_stats' game.id %}">{{ game.name }}</a></td>
                <td>{{ game.gamers.count }}/{{ game.max_players }}</td>
                <td>{{ game.created_at }}</td>
                <td>{{ game.finished_at }}</td>
                <td>
                {% for gamer in game.gamers.all %}
                    {% if forloop.counter0 == 0 %}
                      {% if gamer.winner == True %}
                          <font size="2">{{ gamer.nick }}</font>
                      {% endif %}
                    {% else %}
                      {% if gamer.winner == True %}
                          <font size="2">, {{ gamer.nick }}</font>
                      {% endif %}
                    {% endif %}
                {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>{% trans 'You not have been hosting any finished games' %}.</p>
{% endif %}

<hr>
<h4> {% trans 'Played games' %} </h4>
{% if gamers %}
    <p>{% trans 'You are playing as' %}:</p>
    <table width="50%" height="100%" border="1" cellpadding="2" cellspacing="1" bgcolor="white">
        <tr>
            <th> {% trans 'Nick' %} </th>
            <th> {% trans 'Game name' %} </th>
            <th> {% trans 'Game code' %} </th>
            <th> {% trans 'Game host' %} </th>
            <th> {% trans 'Players' %} </th>
            <th> {% trans 'Game created at' %}</th>
        </tr>
        {% for gamer in gamers %}
            <tr>
                <td>{{ gamer.nick }}</td>
                <td><a href="{% url 'games:game_stats' gamer.game.id %}">{{ gamer.game.name }}</a></td>
                <td>{{ gamer.game.game_code }}</td>
                <td>{{ gamer.game.host.username }}</td>
                <td>{{ gamer.game.gamers.count }}/{{ gamer.game.max_players }}</td>
                <td>{{ gamer.game.created_at }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>{% trans 'You are not playing any games as gamer' %}.</p>
{% endif %}

<br />

{% if gamers_end %}
    <p>{% trans 'You have been playing as' %}:</p>
    <table width="50%" height="100%" border="1" cellpadding="2" cellspacing="1" bgcolor="white">
        <tr>
            <th> {% trans 'Nick' %} </th>
            <th> {% trans 'Game name' %} </th>
            <th> {% trans 'Game host' %} </th>
            <th> {% trans 'Players' %} </th>
            <th> {% trans 'Game created at' %}</th>
            <th> {% trans 'Game finished at' %}</th>
        </tr>
        {% for gamer in gamers_end %}
            <tr>
                <td>{{ gamer.nick }}</td>
                <td><a href="{% url 'games:game_stats' gamer.game.id %}">{{ gamer.game.name }}</a></td>
                <td>{{ gamer.game.host.username }}</td>
                <td>{{ gamer.game.gamers.count }}/{{ gamer.game.max_players }}</td>
                <td>{{ gamer.game.created_at }}</td>
                <td>{{ gamer.game.finished_at }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>{% trans 'You not have been playing any finished games as gamer' %}.</p>
{% endif %}
{% endblock %}