e_munchkin/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('games/', include("games.urls")),
    path('', views.index, name='home'),
]

games/urls.py
from django.urls import path

from .views import view_encyclopedia
from .views import view_create_game
from .views import view_delete_gamer
from .views import view_edit_game
from .views import view_edit_gamer_order
from .views import view_edit_gamer
from .views import view_end_game
from .views import view_game_access
from .views import view_game_panel
from .views import view_gamer
from .views import view_help
from .views import view_kick_gamer
from .views import view_stats_game
from .views import view_update_stats

#from . import views as views

app_name = 'games'
urlpatterns = [
    # ex: /games/
    # path('', views.IndexView.as_view(), name='index'),
    path('encyclopedia/', view_encyclopedia.encyclopedia_view, name='encyclopedia'),

    # ex: /games/create/
    path('create/', view_create_game.CreateGameView.as_view(), name='create_game'),
    # ex: /games/1
    path('<int:pk>/', view_game_panel.GamePanelView.as_view(), name='game_panel'),
    # ex: /games/1/edit
    path('<int:pk>/edit/', view_edit_game.EditGameView.as_view(), name='edit_game'),
    # ex: /games/1/edit/gamer/order
    path('<int:pk>/edit/gamer/order', view_edit_gamer_order.EditGamerOrderView.as_view(), name='edit_gamer_order'),
    # ex: /games/1/end
    path('<int:pk>/end/', view_end_game.EndGameView.as_view(), name='end_game'),
    # ex: /games/1/edit/gamer/
    path('<int:pk>/edit/gamer/', view_edit_gamer.EditGamerView.as_view(), name='edit_gamer'),
    # ex: /games/1/end/update
    path('<int:pk>/end/update/', view_update_stats.update_stats, name='update_stats'),
    # ex: /games/1/stats
    path('<int:pk>/stats/', view_stats_game.StatsGameView.as_view(), name='game_stats'),

    # ex: /games/access/
    path('access/', view_game_access.GameAccessView.as_view(), name='game_access'),
    # ex: /games/ABCD/Humbert/join_game/
    # path('<gamepass>/<nick>/join_game/', views.join_game, name='join_game'),
    # ex: /games/gamer/5/
    path('gamer/<int:pk>/', view_gamer.GamerView.as_view(), name='gamer'),
    # ex: /games/gamer/5/lave
    path('gamer/<int:pk>/leave/', view_delete_gamer.DeleteGamerView.as_view(), name='delete_gamer'),
    # ex: /games/gamer/5/kick
    path('gamer/<int:pk>/kick/', view_kick_gamer.KickGamerView.as_view(), name='kick_gamer'),
    # ex: /games/help/
    path('help/', view_help.help_view, name='help')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

    {% load i18n %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <meta charset="utf-8">

  <meta name="description" content="Free Web tutorials">
  <meta name="keywords" content="HTML,CSS,XML,JavaScript">
  <meta name="author" content="John Doe">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title %}e_munchkin{% endblock %}</title>
  <style>
    body{
        background: #FCD697
    }
  </style>
        <link rel="stylesheet" type="text/css" href="{% static 'background.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'button.css' %}" />

</head>
<body>
  <header>
    {% if user.is_authenticated %}

        <table align="center">
        <tr><br /></tr>
        <tr>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'logout' %}">{% trans 'Logout' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'home' %}">{% trans 'Home' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'user_stats' user.id %}">{% trans 'Stats' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'edit_profile' %}">{% trans 'Account' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'games:help' %}">{% trans 'Help' %}</a></td>
        </tr>
        </table>

    {% else %}

        <table align="center">
        <tr><br /></tr>
        <tr>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'home' %}">{% trans 'Home' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'login' %}">{% trans 'Login' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'signup' %}">{% trans 'SignUp' %}</a></td>
             <td style="padding:0 15px 0 15px;"><a href="{% url 'games:help' %}">{% trans 'Help' %}</a></td>
        </tr>
        </table>

    {% endif %}

  </header>
  <hr>
  <main>
<div align="center">
    {% block content %}
    {% endblock %}
</div>
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}e_munchkin{% endblock %}

{% block content %}

    <h1>{% trans 'Web application e_munchkin' %}</h1>
    <br />

    {% if user.is_authenticated %}
      <h4>{% trans 'Welcome' %} <font color="orange">{{ user.username }}</font>!
          <br /> {% trans 'Join us and play with us' %}.
      </h4>
      <br />

      <form action="{% url 'games:create_game' %}">
          <input type="submit" value="{% trans 'Host game' %}" class="blue_button"/>
      </form>
      <br />

    {% else %}

      <h4>{% trans 'Welcome' %} <font color="orange"> {% trans 'mysterious stranger' %}</font>!
          <br /> {% trans 'Join us and play with us' %}.
      </h4>
      <br />

    {% endif %}

     <form action="{% url 'games:game_access' %}">
        <input type="submit" value="{% trans 'Join an existing game' %}" class="green_button"/>
     </form>

    <br />
    <br />
    <p>{% trans 'You have visited this page' %} {{ num_visits }} {% if num_visits == 1 %}{% trans 'time' %}{% else %}{% trans 'times' %}{% endif %}.</p>

{% endblock %}